version: '3.8'

services:
  iimp-web:
    build: .
    ports:
      - "80:80"
    environment:
      - ENVIRONMENT=production
    volumes:
      - ./backend:/app/backend
      - ./frontend:/var/www/html
    restart: unless-stopped
    container_name: iimp-checkout-system

  validation-api:
    build: .
    ports:
      - "8001:8001"
    environment:
      - ENVIRONMENT=production
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - ./backend:/app/backend
    restart: unless-stopped
    container_name: iimp-validation-api
    command: ["python", "/app/backend/validation_api.py"]

  # Development service with hot reload
  iimp-dev:
    build: .
    ports:
      - "8080:80"
    environment:
      - ENVIRONMENT=development
    volumes:
      - ./backend:/app/backend
      - ./frontend:/var/www/html
    profiles:
      - dev
    container_name: iimp-checkout-dev